plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
remote_theme: csik/jek
collections:
  classes:
    output: true
    permalink: /classes/:path/
url: "https://courses.infosci.cornell.edu"
baseurl: "/info4240/2021fa"
title: "4240_Syllabus"
