plugins:
 - jekyll-remote-theme # add this line to the plugins list if you already have one
 - jekyll-feed
remote_theme: csik/jek
collections:
  classes:
    output: true
    permalink: /classes/:path/
baseurl: "/info4240/2021fa"
url: "https://courses.infosci.cornell.edu"
title: "4240_Syllabus"
